### ISSUE TITLE
Stackdriver agent deployment on Debian is failing.

### ISSUE THREAD

**Issue by suhas22** [GoogleCloudPlatform/stackdriver-ansible-role#10]
Hi there,
Until last week or so stackdriver installation was working absolutely fine without any issues, but today i am getting an error, saying the package stackdriver-agent cannot be found.
Is it been moved to a different location or is the package name changed ? Can you pls help here.
I did do a fresh clone of this repo and tried again, but the same issue. 

![image](https://cloud.githubusercontent.com/assets/16332828/13348889/31dd96b8-dc9c-11e5-963f-d381617a2686.png)

**Comment by rimey** [comment]
I can check. What Debian release are you running (e.g., as reported by "lsb_release -sc")?

Ken

**Comment by suhas22** [comment]
Hi,
I am on Debian Jessie 8.3

**Comment by rimey** [comment]
I tried it on Jessie (on GCP, but that shouldn't matter) and did not get an error. Could the problem have been transient?

Ken

**Comment by dhrupadb** [comment]
Closing this as a stale issue.
