### ISSUE TITLE
get "msg: Unable to send msg: HTTP Error 401: Unauthorized" when running role in first time

### ISSUE THREAD

**Issue by yarivgraf** [GoogleCloudPlatform/stackdriver-ansible-role#2]
Hi,
I'm running the role as a park of a playbook on gce instance.
- { role: stackdriver-ansible-role, stackdriver_api_key: '{{api_key}}', stackdriver_mongodb_enabled: yes }

I have mongo already installed and running.
When I run the role in first time, it throws me this exception:

NOTIFIED: [stackdriver | restart collectd] ************************************ 
changed: [yg-test] => {"changed": true, "name": "stackdriver-agent", "state": "started"}

NOTIFIED: [stackdriver | restart extractor] *********************************** 
changed: [yg-test] => {"changed": true, "name": "stackdriver-extractor", "state": "started"}

NOTIFIED: [stackdriver | stackdriver updated] ********************************* 
failed: [yg-test -> 127.0.0.1] => {"changed": false, "failed": true}
msg: Unable to send msg: HTTP Error 401: Unauthorized

FATAL: all hosts have already failed -- aborting

In second run, I don't see any errors probably there is no update to run.

Thanks.
Keep up the good work!

**Comment by rimey** [comment]
The error is about a failure to contact the Stackdriver gateway, which will also prevent your agent from sending data. This could, for instance, be caused by an invalid API key. You can test directly by SSHing into the host and executing `sudo /opt/stackdriver/stack-config info`. The first few lines of output should look like this:

```
Stackdriver Host Info Dump
Resource Id: [...]
API Key: [...]
Customer ID: [...]
```

**Comment by yarivgraf** [comment]
I get : 
Error talking to Stackdriver gateway No JSON object could be decoded
But within the gce project, in the monitor section I can view the stackdriver info and looks ok.

**Comment by rimey** [comment]
You may see the instance and its CPU usage, which the GCE infrastructure reports, but you won't see memory usage if data is not being received from the agent.

**Comment by yarivgraf** [comment]
I can see all processes details includes mongo memory usage,connections an operations.

BTW, in the handlers/main.yml I changed the "stackdriver update" to:
- name: stackdriver updated
  service: name=stackdriver-agent state=restarted

**Comment by rimey** [comment]
Thank you for reporting this. It's exactly as you said. I failed to reproduce it at first because the issue only affects Google Cloud Monitoring, and not generic Stackdriver. I will be following up.

**Comment by rimey** [comment]
This feature is now controlled by the value of `stackdriver_events_enabled`, which defaults to `no`.
