### ISSUE TITLE
Ubuntu14 Install requires sudo to be explicitly specified

### ISSUE THREAD

**Issue by gmalouf** [GoogleCloudPlatform/stackdriver-ansible-role#3]
When I tried to install to my Ubuntu14 EC2 instance, I was getting:

TASK: [rimey.stackdriver | [Debian] Enable the Stackdriver apt repository.] *** 
failed: [52.1.6.25] => {"failed": true}
msg: [Errno 13] Permission denied: '/etc/apt/sources.list.d/.repo_stackdriver_com_apt.list-KMRJAL'

FATAL: all hosts have already failed -- aborting

Adding 'sudo: true' when declaring the role fixed the issue.  May want to consider updating the documentation to reflect this.

**Comment by rimey** [comment]
Done. The omission was an oversight. Thank you!
