### ISSUE TITLE
Add debian jessie to supported platforms

### ISSUE THREAD

**Issue by daurnimator** [GoogleCloudPlatform/stackdriver-ansible-role#4]
Currently only wheezy is listed.

**Comment by rimey** [comment]
I added jessie to the list of supported Debian versions in the Galaxy metadata. Please let me know if you ran into some kind of problem with jessie.

**Comment by daurnimator** [comment]
I was already satisfactorily running it against jessie since I asked for them to add the jessie apt repo. It was just the metadata left :)

Fixed with 6efd287aac59b6f38369e97098516de6f9f5d84c
