### ISSUE TITLE
Can't install on Ubuntu 15.04

### ISSUE THREAD

**Issue by winduptoy** [GoogleCloudPlatform/stackdriver-ansible-role#6]
When installing on Ubuntu 15.04, Ansible was reporting the following error: `No package matching 'stackdriver-agent' is available`

I changed [Line 17 of tasks/Debian.yml](https://github.com/GoogleCloudPlatform/stackdriver-ansible-role/blob/1f21c76c4cb89c540da3b3439cdba40d7afed32b/tasks/Debian.yml#L17) to read: `repo: "deb {{ stackdriver_package_repo }} trusty main"` which worked.

I believe that Stackdriver does not have an apt repo for Ubuntu 15.04.

Any ideas how to fix this?

**Comment by rimey** [comment]
As you say, there is no agent package in the vivid repo. This is a known issue, and I have sent a reminder about it to the responsible people.

In the meantime, your workaround looks perfectly reasonable.
