### ISSUE TITLE
"Include OS-specific variables." step in tasks/main.yml failing

### ISSUE THREAD

**Issue by bogdanghervan** [GoogleCloudPlatform/stackdriver-ansible-role#8]
The "Include OS-specific variables." step in tasks/main.yml fails with the error "No source file given".

I'm using Ansible 1.9.3. I'm installing the role globally using `ansible-galaxy install rimey.stackdriver`, which puts it under `/etc/ansible/roles`.

Is it something that I'm doing wrong?

Relevant syslog entries:
```
Oct  6 12:59:23 play-4 startupscript: TASK: [rimey.stackdriver | Check that the Stackdriver API key has been specified.] *** 
Oct  6 12:59:23 play-4 startupscript: skipping: [127.0.0.1]
Oct  6 12:59:23 play-4 startupscript: 
Oct  6 12:59:23 play-4 startupscript: TASK: [rimey.stackdriver | Include OS-specific variables.] ******************** 
Oct  6 12:59:23 play-4 startupscript: failed: [127.0.0.1] => {"failed": true, "item": null}
Oct  6 12:59:23 play-4 startupscript: msg: No source file given
Oct  6 12:59:23 play-4 startupscript: 
Oct  6 12:59:23 play-4 startupscript: FATAL: all hosts have already failed -- aborting
```

**Comment by rimey** [comment]
What kind of system is this?

**Comment by bogdanghervan** [comment]
I just figured it out. I had fact gathering explicitly turned off (`gather_facts: no`) in my playbook, so both `ansible_os_family` and `ansible_distribution` were undefined. Sorry for the confusion.

**Comment by rimey** [comment]
No problem. I'm glad you got it figured out quickly.
